year: "2008"
votes_file: "data/raw/2008/10020803.DAT"
partidos_dir: "data/partidos/2008"
geographic_dir: "data/geographic/spain2011"
base_constituencies_dir: "data/geographic/spain2011/constituencies"
output: "output/mapa2008"
method: "transfer"
width: 1100
height: 900
map: "png"
