year: "2011"
votes_file: "data/raw/2011/10021111.DAT"
partidos_dir: "data/partidos/2011"
map_template: "data/mapas/molde/SECC_CPV_E_20111101_01_R_INE"
output: "output/mapa2011"
method: "transfer"
width: 1100
height: 900
skip_map: false
no_map: false
