year: "2019a"
votes_file: "data/raw/2019a/10021904.DAT"
partidos_dir: "data/partidos/2019a"
map_template: "data/mapas/molde/SECC_CPV_E_20111101_01_R_INE"
output: "output/mapa2019a"
method: "transfer"
width: 1100
height: 900
skip_map: false
no_map: false
